MVCBasico/Models/Movimiento.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MVCBasico.Models
{
    public class Movimiento
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public DateTime Fecha { get; set; }

        public string Descripcion { get; set; }

        [DataType(DataType.Currency)]
        public double Importe { get; set; }

        public int CuentaId { get; set; }
    }
}

MVCBasico/Controllers/MovimientoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVCBasico.Context;
using MVCBasico.Models;
using MVCBasico.Utils;

namespace MVCBasico.Controllers
{
    [ValidarSesion]
    public class MovimientoController : Controller
    {
        private readonly EscuelaDatabaseContext _context;

        public MovimientoController(EscuelaDatabaseContext context)
        {
            _context = context;
        }

        // GET: Movimiento
        public async Task<IActionResult> Index(string? error)

        {
            if (!(error is null))
            {
                ModelState.AddModelError(string.Empty, error);
            }


            List<Cuenta> cuentas =  await _context.Cuentas.Include(cuenta => cuenta.Movimientos)
                .Where(cuenta => cuenta.UsuarioId == HttpContext.Session.GetInt32("Usuario")).ToListAsync();

            return View(cuentas[0].Movimientos.OrderByDescending(movimiento => movimiento.Fecha));
        }



        // GET: Movimiento/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movimiento = await _context.Movimientos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movimiento == null)
            {
                return NotFound();
            }

            return View(movimiento);
        }

        // GET: Movimiento/Create
        public IActionResult Create()
        {
            
            return PartialView();
        }

        // POST: Movimiento/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create (MovimientoRequest movimientoRequest)
        {
            if (ModelState.IsValid)
            {
                Cuenta cuenta = _context.Cuentas.Where(cuenta => cuenta.UsuarioId == HttpContext.Session.GetInt32("Usuario")).First();

                if (cuenta.Saldo + movimientoRequest.Importe < 0)
                {
                    return RedirectToAction(nameof(Index), new { error = "No tiene suficiente dinero"});
                }


                cuenta.Saldo += movimientoRequest.Importe;
                Movimiento movimiento = new Movimiento()
                {
                    Fecha = movimientoRequest.Fecha,
                    Descripcion = movimientoRequest.Descripcion,
                    Importe = movimientoRequest.Importe
                };
                cuenta.Movimientos.Add(movimiento);
                _context.Update(cuenta);

                agregarPuntos(movimientoRequest.Importe);

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index), new { error = "Hubo un error" });
        }

        private void agregarPuntos(double importe)
        {
            Puntos puntos = _context.Puntos.Where(puntos => puntos.UsuarioId == HttpContext.Session.GetInt32("Usuario")).First();

            if (importe > 5000)
            {
                puntos.CantPuntos += Constants.PUNTOS_POR_INGRESO;
            }

            if (importe < 0)
            {
                double saldo = puntos.SaldoRemanente + importe * -1;
                puntos.CantPuntos += ((int)(saldo / Constants.PRECIO_PUNTO));
                puntos.SaldoRemanente = saldo % Constants.PRECIO_PUNTO;
            }

            _context.Update(puntos);
        }

        // GET: Movimiento/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movimiento = await _context.Movimientos.FindAsync(id);
            if (movimiento == null)
            {
                return NotFound();
            }
            return View(movimiento);
        }

        // POST: Movimiento/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Fecha,Descripcion,Importe,CuentaId")] Movimiento movimiento)
        {
            if (id != movimiento.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movimiento);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovimientoExists(movimiento.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movimiento);
        }

        // GET: Movimiento/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movimiento = await _context.Movimientos
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movimiento == null)
            {
                return NotFound();
            }

            return View(movimiento);
        }

        // POST: Movimiento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movimiento = await _context.Movimientos.FindAsync(id);
            _context.Movimientos.Remove(movimiento);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovimientoExists(int id)
        {
            return _context.Movimientos.Any(e => e.Id == id);
        }
    }
}

MVCBasico/Views/Movimiento/Create.cshtml
@model MVCBasico.Models.MovimientoRequest

@{
    ViewData["Title"] = "Create";
    Layout = "";
}
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<!--Modal Body Start-->

<div class="modal-content">

    <!--Modal Header Start-->
    <div class="modal-header">
        <h4 class="modal-title">Nuevo Movimiento</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
    <!--Modal Header End-->


    <form asp-action="Create" asp-controller="Movimiento" method="post" enctype="multipart/form-data">

        @Html.AntiForgeryToken()

        <div class="modal-body form-horizontal">
            <div class="form-group row">
                @Html.LabelFor(model => model.Fecha, new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    <input asp-for="@Model.Fecha" placeholder="Fecha" class="form-control" />
                    <span asp-validation-for="Fecha" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.Importe, new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    <input asp-for="@Model.Importe" class="form-control" placeholder="Importe" />
                    <span asp-validation-for="Importe" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.Descripcion, new { @class = "col-sm-2 col-form-label" })
                <div class="col-sm-10">
                    <input asp-for="@Model.Descripcion" class="form-control" placeholder="Descripcion" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
            </div>


        </div>
        <!--Modal Footer Start-->
        <div class="modal-footer">
            <button data-dismiss="modal" id="cancel" class="btn btn-default" type="button">Cancel</button>
            <button class="btn btn-success relative" id="btnSubmit" type="submit">
                <i class="loader"></i>
                Crear
            </button>
        </div>
        <!--Modal Footer End-->
    </form>

</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

<!--Modal Body End-->

MVCBasico/Views/Movimiento/Delete.cshtml
@model MVCBasico.Models.Movimiento

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movimiento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Importe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Importe)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MVCBasico/Views/Movimiento/Details.cshtml
@model MVCBasico.Models.Movimiento

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movimiento</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Importe)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Importe)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MVCBasico/Views/Movimiento/Edit.cshtml
@model MVCBasico.Models.Movimiento

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Movimiento</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <input asp-for="Descripcion" class="form-control" />
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Importe" class="control-label"></label>
                <input asp-for="Importe" class="form-control" />
                <span asp-validation-for="Importe" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CuentaId" class="control-label"></label>
                <select asp-for="CuentaId" class="form-control" asp-items="ViewBag.CuentaId"></select>
                <span asp-validation-for="CuentaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MVCBasico/Views/Movimiento/Index.cshtml
@model IEnumerable<MVCBasico.Models.Movimiento>

@{
    Layout = "HomeLayout";
    ViewData["Title"] = "Movimientos | Banco PNT";
}
<link href="~/css/styleMovimientos.css" rel='stylesheet'>
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
<main>
    <h1>Movimientos</h1>
    <table>
        <thead>
            <tr>
                <th>Fecha</th>
                <th>Detalle</th>
                <th>Importe</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Fecha)</td>
                    <td>@Html.DisplayFor(modelItem => item.Descripcion)</td>
                    <td>@Html.DisplayFor(modelItem => item.Importe)</td>
                </tr>
            }

        </tbody>
    </table>
    <div asp-validation-summary="ModelOnly" class="text-danger input-contenedor"></div>
    <a class="btn btn-primary popup" data-url="Create" data-toggle="modal" data-target="#modal-create-movimiento" id="MovimientoModel">Nuevo</a>
    <partial name="Modal" />
</main>
<script src="~/js/Movimientos.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/modal.js" asp-append-version="true"></script>

  